"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Event is the parent class of all events generated by controls.
 */
var Event = /** @class */ (function () {
    function Event(name, value) {
        this.name = name;
        this.value = value;
    }
    return Event;
}());
exports.Event = Event;
//# sourceMappingURL=Event.js.map